version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/venv
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=True
    env_file:
      - .env

  # Optional: Add Redis for caching/sessions
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  # Optional: Add PostgreSQL for production database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=retailgenie
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
