services:
  - type: web
    name: retailgenie-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false